In [169]:
import numpy as np
import scipy.stats as st
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
import pandas as pd
import csv


from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report

ModuleNotFoundError: No module named 'writematrix'

In [155]:
import warnings
import sklearn.exceptions
warnings.filterwarnings("ignore", category=sklearn.exceptions.UndefinedMetricWarning)

# Base-MLP: a baseline Multi-Layered Perceptron with 1 hidden layer of 100 neurons, sigmoid/logistic as activation function, stochastic gradient descent, and default values for the rest of the parameters. 

In [156]:
my_hidden_layer = 100
my_activation_function = 'logistic'
my_solver = 'sgd'

# 1.Dataset 1

In [157]:
training_ds1 = pd.read_csv("Assig1-Dataset/train_1.csv", sep=",", header=None)
testing_ds1 = pd.read_csv("Assig1-Dataset/test_with_label_1.csv", sep=",",header=None)

In [158]:
training_features = training_ds1.drop(training_ds1.columns[-1],axis=1)
training_targets = training_ds1[training_ds1.columns[-1]]

testing_features = testing_ds1.drop(training_ds1.columns[-1],axis=1)
testing_targets = testing_ds1[training_ds1.columns[-1]]

## Training / Prediction

In [159]:
base_MLP = MLPClassifier(hidden_layer_sizes= my_hidden_layer, activation=my_activation_function, solver=my_solver).fit(training_features, training_targets)

C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [160]:
predicted_base_MLP = base_MLP.predict(testing_features)

## (b) a plot the confusion matrix

In [161]:
base_MLP_confusion_matrix = confusion_matrix(testing_targets, predicted_base_MLP)
print(base_MLP_confusion_matrix)

[[2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

## (c)(d) the precision, recall, and f1-measure for each class 

In [162]:
base_MLP_classification_report = classification_report(testing_targets, predicted_base_MLP,output_dict=True)
print(classification_report(testing_targets, predicted_base_MLP))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         4
           1       0.00      0.00      0.00         2
           2       0.60      0.75      0.67         4
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         2
           6       0.75      0.75      0.75         4
           7       1.00      0.33      0.50         3
           8       0.33      1.00      0.50         3
           9       0.67      0.50      0.57         4
          10       0.25      0.67      0.36         3
          11       1.00      0.75      0.86         4
          12       0.50      1.00      0.67         3
          13       0.30      0.75      0.43         4
          14       0.30      1.00      0.46         3
          15       0.00      0.00      0.00         3
          16       1.00      0.67      0.80         3
          17       0.23    

# e) Writing to .csv


In [258]:
filename = './outputs/Base-MLP/Base-MLP-DS1.csv'


with open(filename, "w", newline="") as file:
    writer = csv.writer(file) 
    base_MLP_results = np.arange(1, predicted_base_MLP.shape[0])
    writer.writerow(["Predicted Results:"])
    for i in zip(np.arange(1, predicted_base_MLP.shape[0]), predicted_base_MLP):
        writer.writerow([i])
    writer.writerow("")

with open(filename, 'a') as file:
    writer = csv.writer(file)    
    
    df = pd.DataFrame(base_MLP_confusion_matrix)
    df.to_csv(filename,index=False, header = False, mode = 'a')
    writer.writerow("")
    
with open(filename, 'a') as file:
    writer = csv.writer(file)    
    
    df = pd.DataFrame(base_MLP_classification_report).transpose()
    df.to_csv(filename, mode = 'a')

ValueError: DataFrame constructor not properly called!

# 2.Dataset 2


In [138]:
training_ds2 = pd.read_csv("Assig1-Dataset/train_2.csv", sep=",", header=None)
testing_ds2 = pd.read_csv("Assig1-Dataset/test_with_label_2.csv", sep=",",header=None)

In [139]:
training_features2 = training_ds2.drop(training_ds2.columns[-1],axis=1)
training_targets2 = training_ds2[training_ds2.columns[-1]]

testing_features2 = testing_ds2.drop(training_ds2.columns[-1],axis=1)
testing_targets2 = testing_ds2[training_ds2.columns[-1]]

In [140]:
base_MLP2 = MLPClassifier(hidden_layer_sizes= my_hidden_layer, activation=my_activation_function, solver=my_solver).fit(training_features2, training_targets2)

C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [196]:
predicted_base_MLP2 = base_MLP2.predict(testing_features2)

## (b) a plot the confusion matrix

In [253]:
base_MLP_confusion_matrix2 = confusion_matrix(testing_targets2, predicted_base_MLP2)
print(base_MLP_confusion_matrix2)

[[ 45   3   1   0   1   2   0   0   1   2]
 [  3 119   0   1   0   1   0   0   1   0]
 [  0   0   6   0   0   1   0   0   7   1]
 [  2   2   0   9   0   2   0   0   0   0]
 [  4   1   0   0  29   2   0   0   3  11]
 [  0   0   0   0   1  50   0   0   0   4]
 [  2   4   1   0   1   0   5   0   1   1]
 [  0   0   0   0   0   0   0  15   0   0]
 [  1   1   0   0   0   0   0   0  44   4]
 [  2   0   0   0   9   5   0   0   1 108]]


## (c)(d) the precision, recall, and f1-measure for each class 

In [260]:
base_MLP_classification_report2 = classification_report(testing_targets2, predicted_base_MLP2, output_dict=True)
print(classification_report(testing_targets2, predicted_base_MLP2))

              precision    recall  f1-score   support

           0       0.76      0.82      0.79        55
           1       0.92      0.95      0.93       125
           2       0.75      0.40      0.52        15
           3       0.90      0.60      0.72        15
           4       0.71      0.58      0.64        50
           5       0.79      0.91      0.85        55
           6       1.00      0.33      0.50        15
           7       1.00      1.00      1.00        15
           8       0.76      0.88      0.81        50
           9       0.82      0.86      0.84       125

    accuracy                           0.83       520
   macro avg       0.84      0.73      0.76       520
weighted avg       0.83      0.83      0.82       520



# e) Writing to .csv

In [257]:
filename2 = './outputs/Base-MLP/Base-MLP-DS2.csv'


with open(filename2, "w", newline="") as file:
    writer = csv.writer(file) 
    base_MLP_results2 = np.arange(1, predicted_base_MLP2.shape[0])
    writer.writerow(["Predicted Results:"])
    for i in zip(np.arange(1, predicted_base_MLP2.shape[0]), predicted_base_MLP2):
        writer.writerow([i])
    writer.writerow("")

with open(filename2, 'a') as file:
    writer = csv.writer(file)    
    
    df = pd.DataFrame(base_MLP_confusion_matrix2)
    df.to_csv(filename2,index=False, header = False, mode = 'a')
    writer.writerow("")
    
with open(filename2, 'a') as file:
    writer = csv.writer(file)    
    
    df = pd.DataFrame(base_MLP_classification_report2).transpose()
    df.to_csv(filename2, mode = 'a')