### Imports needed for decision trees

In [221]:
import pandas as pd
import numpy as np
import csv
%matplotlib inline

#imports for DT
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

#remove warnings
import warnings
warnings.filterwarnings("ignore")

## Base-DT 

From the results of the decision tree models created, the second data set seems to have much better predictions, and overall has better performance in terms of recall, precision, f1-measure. This is probably due to the fact that there are only 9 classes and 520 instances. In comparison to data set 1 which has 26 classes and only 80 instances. This allows for the training model to produce better predictions overall, since more instances are available. 

## Data Set 1 

In [211]:
#Retrieve test data for dataset1 from csv file
test_set1 = pd.read_csv("Assig1-Dataset/test_with_label_1.csv", header=None)
#test_set1.shape #display number of (rows, columns) to ensure all the data was retrieved

#seperate values/labels from the test data
y_test1 = test_set1[1024] #the set of labels to all the data in x_test
x_test1 = test_set1.drop(1024, axis=1) #test data set

#Retrieve train set data for dataset1 from csv file
train_set1 = pd.read_csv("Assig1-Dataset/train_1.csv", header=None)

#seperate values/labels from the train data
target_train1 = train_set1[1024] #y_train, the set of labels to all the data in x_train
x_train1 = train_set1.drop(1024,axis=1) #the training data set

## Training / Prediction

In [212]:
#create model for ds1
dtree1 = DecisionTreeClassifier(criterion = "entropy") #Use entropy as the decision criterion for the tree, all other values are set to default
dtree1 = dtree1.fit(x_train1, target_train1) #fit is used to train the algo based on the training data
dt_pred1 = dtree1.predict(x_test1) #predictions based on the test data

## Plot confusion matrix

In [213]:
#print confustion matrix
print(confusion_matrix(y_test1, dt_pred1))

[[3 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 

## Print Classification Report: Precision, Recall, F-1 Measure for each class

In [214]:
#print classificaton report
print(classification_report(y_test1, dt_pred1))

              precision    recall  f1-score   support

           0       0.60      0.75      0.67         4
           1       0.00      0.00      0.00         2
           2       0.60      0.75      0.67         4
           3       0.50      0.33      0.40         3
           4       0.33      0.50      0.40         2
           5       0.50      0.50      0.50         2
           6       0.20      0.25      0.22         4
           7       1.00      0.33      0.50         3
           8       1.00      0.33      0.50         3
           9       0.75      0.75      0.75         4
          10       0.00      0.00      0.00         3
          11       1.00      0.75      0.86         4
          12       0.00      0.00      0.00         3
          13       0.40      0.50      0.44         4
          14       0.67      0.67      0.67         3
          15       0.40      0.67      0.50         3
          16       1.00      0.33      0.50         3
          17       0.67    

C:\Users\admin\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Data Set 2

In [215]:
#Retrieve test data for dataset2 from csv file
test_set2 = pd.read_csv("Assig1-Dataset/test_with_label_2.csv", header=None)

#seperate values/labels from the test data
y_test2 = test_set2[1024] #the set of labels to all the data in x_test
x_test2 = test_set2.drop(1024, axis=1) #test data set

#Retrieve training data for dataset2 from csv file
train_set2 = pd.read_csv("Assig1-Dataset/train_2.csv", header=None)

#seperate values/labels from the test data
target_train2 = train_set2[1024] #y_train, the set of labels to all the data in x_train
x_train2 = train_set2.drop(1024,axis=1) #the training data set


## Training / Prediction

In [216]:
#create model for ds2
dtree2 = DecisionTreeClassifier(criterion = "entropy") #Use entropy as the decision criterion for the tree, all other values are set to default
dtree2 = dtree2.fit(x_train2, target_train2) #fit is used to train the algo based on the training data
dt_pred2 = dtree2.predict(x_test2) #predictions based on the test data

## Plot Confusion Matrix

In [217]:
#print out confusion matrix
print(confusion_matrix(y_test2, dt_pred2))

[[ 45   3   0   0   3   1   0   0   0   3]
 [  2 113   0   3   2   2   1   0   2   0]
 [  0   0   8   0   2   2   0   0   2   1]
 [  0   3   0   9   0   2   0   1   0   0]
 [  3   4   0   2  25   2   1   0   1  12]
 [  0   1   0   1   2  41   0   0   0  10]
 [  1   0   2   0   1   1   7   0   2   1]
 [  0   2   0   0   0   0   0  12   1   0]
 [  1   0   0   1   2   0   1   0  43   2]
 [  2   1   3   0   6  12   0   0   1 100]]


## Print Classification Report: Precision, Recall, F-1 Measure for each class

In [218]:
print("\n")
print(classification_report(y_test2, dt_pred2))



              precision    recall  f1-score   support

           0       0.83      0.82      0.83        55
           1       0.89      0.90      0.90       125
           2       0.62      0.53      0.57        15
           3       0.56      0.60      0.58        15
           4       0.58      0.50      0.54        50
           5       0.65      0.75      0.69        55
           6       0.70      0.47      0.56        15
           7       0.92      0.80      0.86        15
           8       0.83      0.86      0.84        50
           9       0.78      0.80      0.79       125

    accuracy                           0.78       520
   macro avg       0.74      0.70      0.72       520
weighted avg       0.77      0.78      0.77       520



## Writing Results to CSV for both data sets

## Creating CSV file Base-DT-DS1

In [219]:
filename = './outputs/Base-DT-DS1.csv'

Base_DT_DS1 = pd.DataFrame(data=dt_pred1)
Base_DT_DS1.index = Base_DT_DS1.index + 1
Base_DT_DS1.to_csv(filename, header=None)

writer = open(filename, 'a')

writer.write("\nConfusion Matrix:\n\n")
writer.write(str(confusion_matrix(y_test1, dt_pred1)))
writer.write("\n\n\n")
writer.write("\nClassification Report:\n\n")
writer.write(str(classification_report(y_test1, y_pred1)))

writer.close()
print("Output file Base-DT-DS1 created!")

Output file Base-DT-DS1 created!


## Creating CSV file Base-DT-DS2

In [220]:
filename = './outputs/Base-DT-DS2.csv'

Base_DT_DS2 = pd.DataFrame(dt_pred2)
Base_DT_DS2.index = Base_DT_DS2.index + 1
Base_DT_DS2.to_csv(filename, header=None)

writer = open(filename, 'a')

writer.write("\nConfusion Matrix:\n\n")
writer.write(str(confusion_matrix(y_test2, dt_pred2)))
writer.write("\n\n\n")
writer.write("\nClassification Report:\n\n")
writer.write(str(classification_report(y_test2, y_pred2)))

writer.close()
print("Output file Base-DT-DS2 created!")

Output file Base-DT-DS2 created
