In [6]:
import numpy as np
import scipy.stats as st
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
import pandas as pd
import csv


from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV


In [30]:
import warnings
import sklearn.exceptions
warnings.filterwarnings("ignore", category=sklearn.exceptions.UndefinedMetricWarning)

# Best-MLP: a better performing Multi-Layered Perceptron found by performing grid search to find the best combination of hyper-parameters. For this, you need to experiment with the following parameter values

1. activation function: sigmoid, tanh, relu and identity 
2. network architectures of your choice: for eg 2 hidden layers with 30+50 nodes, 3 hidden layers with 10+10
3. solver: Adam and stochastic gradient descent 

In [42]:
parameter_space=[
    { 'activation': ['logistic','tanh','relu','identity'], 'hidden_layer_sizes':[(30,50),(10,10,10)], 'solver':['adam','sgd']}
]

# 1.Dataset 1

In [16]:
training_ds1 = pd.read_csv("Assig1-Dataset/train_1.csv", sep=",", header=None)
testing_ds1 = pd.read_csv("Assig1-Dataset/test_with_label_1.csv", sep=",",header=None)

In [33]:
training_features = training_ds1.drop(training_ds1.columns[-1],axis=1)
training_targets = training_ds1[training_ds1.columns[-1]]

testing_features = testing_ds1.drop(training_ds1.columns[-1],axis=1)
testing_targets = testing_ds1[training_ds1.columns[-1]]

## Training / Prediction

In [26]:
mlp = MLPClassifier() #Choose your classifier
clf = GridSearchCV(mlp, parameter_space, verbose=2).fit(training_features, training_targets)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    4.5s remaining:    0.0s


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=   4.6s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=   4.5s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=   4.5s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=   4.6s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=   4.6s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=   1.8s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=   2.0s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=   2.0s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=   1.9s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....
[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=   1.9s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   4.0s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.8s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.8s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.8s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.9s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   2.6s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.0s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   2.9s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.1s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   2.3s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=adam, total=   5.4s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=adam, total=   5.7s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=adam, total=   5.0s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=adam, total=   5.2s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=adam, total=   5.0s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.5s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.6s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.5s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.5s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.5s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.9s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.9s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.8s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.9s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   4.0s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.8s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.8s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.8s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.8s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.8s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=   4.7s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=   4.9s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=   4.8s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=   4.7s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=   4.7s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.6s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.6s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.6s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.6s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.6s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   4.0s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.9s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.9s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   4.0s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...
[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   2.0s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.9s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.9s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.8s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.9s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.8s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...
[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=   4.1s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=   4.4s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=   4.4s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...
[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=   4.3s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=   4.5s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.3s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.3s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.3s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.3s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=   4.3s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.8s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.7s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.7s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.8s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=   3.7s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.6s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.6s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.6s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.7s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:  5.3min finished


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   3.8s


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [34]:
predicted_best_MLP = clf.predict(testing_features)
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'activation': 'identity', 'hidden_layer_sizes': (30, 50), 'solver': 'adam'}


## (b) a plot the confusion matrix

In [39]:
best_MLP_confusion_matrix = confusion_matrix(testing_targets, predicted_best_MLP)
print(best_MLP_confusion_matrix)

[[2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

## (c)(d) the precision, recall, and f1-measure for each class 

In [40]:
best_MLP_classification_report = classification_report(testing_targets, predicted_best_MLP)
print(classification_report(testing_targets, predicted_best_MLP))

              precision    recall  f1-score   support

           0       0.67      0.50      0.57         4
           1       1.00      1.00      1.00         2
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         3
           4       1.00      1.00      1.00         2
           5       1.00      0.50      0.67         2
           6       0.80      1.00      0.89         4
           7       0.67      0.67      0.67         3
           8       1.00      1.00      1.00         3
           9       1.00      0.75      0.86         4
          10       0.67      0.67      0.67         3
          11       1.00      1.00      1.00         4
          12       0.60      1.00      0.75         3
          13       1.00      0.75      0.86         4
          14       1.00      1.00      1.00         3
          15       0.75      1.00      0.86         3
          16       1.00      1.00      1.00         3
          17       0.75    

# e) Writing to .csv


In [57]:
filename = './outputs/Best-MLP-DS1.csv'

MLP_DS1 = pd.DataFrame(predicted_best_MLP)
MLP_DS1.index = MLP_DS1.index + 1 #To follow assignment example
MLP_DS1.to_csv(filename, header=False)

writer = open(filename, 'a')

writer.write("\nConfusion Matrix:\n\n")
writer.write(str(best_MLP_confusion_matrix))
writer.write("\n\n\n")
writer.write("\nClassification Report:\n\n")
writer.write(str(best_MLP_classification_report))

writer.close()

# 2.Dataset 2


In [43]:
training_ds2 = pd.read_csv("Assig1-Dataset/train_2.csv", sep=",", header=None)
testing_ds2 = pd.read_csv("Assig1-Dataset/test_with_label_2.csv", sep=",",header=None)

In [44]:
training_features2 = training_ds2.drop(training_ds2.columns[-1],axis=1)
training_targets2 = training_ds2[training_ds2.columns[-1]]

testing_features2 = testing_ds2.drop(training_ds2.columns[-1],axis=1)
testing_targets2 = testing_ds2[training_ds2.columns[-1]]

In [45]:
clf2 = GridSearchCV(mlp, parameter_space, verbose=2).fit(training_features2, training_targets2)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   34.3s remaining:    0.0s


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=  34.4s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=  34.7s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=  35.0s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=  35.3s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=adam, total=  35.2s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=  34.8s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=  34.6s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=  34.2s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=  34.6s
[CV] activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(30, 50), solver=sgd, total=  34.6s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  31.5s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  31.5s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  31.6s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  31.2s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  31.3s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   9.1s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   7.6s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   8.8s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   8.1s
[CV] activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd 
[CV]  activation=logistic, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=   8.8s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=adam .......
[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solve

C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=adam, total=  36.7s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=adam, total=  36.6s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=adam, total=  36.3s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=  35.4s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=  35.4s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=  35.3s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=  35.0s
[CV] activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(30, 50), solver=sgd, total=  35.1s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  32.5s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...
[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  25.9s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...
[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  27.4s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...
[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  30.6s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  32.4s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  33.3s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  33.2s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  33.2s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  32.0s
[CV] activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=tanh, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  31.2s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=  36.1s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=  37.5s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=  37.5s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=  37.2s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=adam .......


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=adam, total=  36.9s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=  36.0s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=  38.0s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=  36.5s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=  35.9s
[CV] activation=relu, hidden_layer_sizes=(30, 50), solver=sgd ........


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(30, 50), solver=sgd, total=  37.0s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  32.4s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  33.2s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  32.0s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...
[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  30.6s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam ...


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  33.1s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  33.2s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  32.6s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  32.2s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  32.6s
[CV] activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=relu, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  32.0s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...
[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=  16.4s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...
[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=  18.5s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...
[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=  19.7s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...
[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=  23.9s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=adam ...
[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=adam, total=  22.5s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=  33.1s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=  33.3s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=  33.7s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=  32.9s
[CV] activation=identity, hidden_layer_sizes=(30, 50), solver=sgd ....


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(30, 50), solver=sgd, total=  33.8s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  31.4s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 
[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  29.3s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  32.2s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 
[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  24.2s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam 
[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=adam, total=  31.4s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  32.4s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  32.7s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  30.9s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  29.9s
[CV] activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd 


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed: 41.1min finished


[CV]  activation=identity, hidden_layer_sizes=(10, 10, 10), solver=sgd, total=  30.6s


C:\Users\Ben\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [47]:
predicted_best_MLP2 = clf2.predict(testing_features2)
print('Best parameters found:\n', clf2.best_params_)

Best parameters found:
 {'activation': 'tanh', 'hidden_layer_sizes': (30, 50), 'solver': 'sgd'}


## (b) a plot the confusion matrix

In [48]:
best_MLP_confusion_matrix2 = confusion_matrix(testing_targets2, predicted_best_MLP2)
print(best_MLP_confusion_matrix2)

[[ 47   0   0   1   3   1   0   0   2   1]
 [  1 120   0   2   0   0   0   0   2   0]
 [  0   0   8   0   1   1   0   0   5   0]
 [  1   0   0  14   0   0   0   0   0   0]
 [  3   1   0   1  36   1   0   0   1   7]
 [  0   0   1   0   1  51   0   0   0   2]
 [  0   4   1   0   0   0   7   0   1   2]
 [  0   0   0   0   0   0   0  15   0   0]
 [  1   1   0   0   0   1   0   1  46   0]
 [  1   0   2   0   8   6   0   0   4 104]]


## (c)(d) the precision, recall, and f1-measure for each class 

In [49]:
best_MLP_classification_report2 = classification_report(testing_targets2, predicted_best_MLP2)
print(classification_report(testing_targets2, predicted_best_MLP2))

              precision    recall  f1-score   support

           0       0.87      0.85      0.86        55
           1       0.95      0.96      0.96       125
           2       0.67      0.53      0.59        15
           3       0.78      0.93      0.85        15
           4       0.73      0.72      0.73        50
           5       0.84      0.93      0.88        55
           6       1.00      0.47      0.64        15
           7       0.94      1.00      0.97        15
           8       0.75      0.92      0.83        50
           9       0.90      0.83      0.86       125

    accuracy                           0.86       520
   macro avg       0.84      0.81      0.82       520
weighted avg       0.87      0.86      0.86       520



# e) Writing to .csv

In [56]:
filename2 = './outputs/Best-MLP-DS2.csv'

MLP_DS2 = pd.DataFrame(predicted_best_MLP2)
MLP_DS2.index = MLP_DS2.index + 1 #To follow assignment example
MLP_DS2.to_csv(filename2, header=False)

writer = open(filename2, 'a')

writer.write("\nConfusion Matrix:\n\n")
writer.write(str(best_MLP_confusion_matrix2))
writer.write("\n\n\n")
writer.write("\nClassification Report:\n\n")
writer.write(str(best_MLP_classification_report2))

writer.close()