## Imports needed for decision trees

In [40]:
import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Imports for DT
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

# Best-DT

The BEST-DT-1 performed slighlty better in comparison to the BASE-DT-DS1 model, while the BEST-DT-2 performed slightly worse in comparison to the BASE-DT-DS2 model.

Data Set 1: 
The model never correctly classified the letter 'Z', 'Q' or 'B'.

# 1. Data Set 1

In [41]:
#Retrieve test data for dataset1 from csv file
test_set1 = pd.read_csv("Assig1-Dataset/test_with_label_1.csv", header=None)

#seperate values/labels from the test data
y_test1 = test_set1[1024] #the set of labels to all the data in x_test
x_test1 = test_set1.drop(1024, axis=1) #test data set

#Retrieve train set data for dataset1 from csv file
train_set1 = pd.read_csv("Assig1-Dataset/train_1.csv", header=None)

#seperate values/labels from the train data
target_train1 = train_set1[1024] #y_train, the set of labels to all the data in x_train
x_train1 = train_set1.drop(1024,axis=1) #the training data set

## Setting Classifier Parameters and creating model

In [42]:
#Setting Classifier parameters
parameters = {'criterion': ['gini', 'entropy'],
              'max_depth': [10, None],
              'min_samples_split': [1,2,3,4,5,6,7,8,9,10],
              'min_impurity_decrease': [0.0,0.1, 0.2, 0.3, 0.4],
              'class_weight': ['none', 'balanced']}

#DecisionTreeClassifier
clf = GridSearchCV(estimator=DecisionTreeClassifier(), param_grid=parameters, n_jobs=-1)

best_dt_1 = clf.fit(x_train1, target_train1) #fit is used to train the algo based on the training data
best_dt_pred1 = best_dt_1.predict(x_test1) #predictions based on the test data

## Display best hyperparameters

In [43]:
#print best hyperparameters
print("Best parameters: ")
print(best_dt_1.best_params_)

Best parameters: 
{'class_weight': 'balanced', 'criterion': 'gini', 'max_depth': None, 'min_impurity_decrease': 0.0, 'min_samples_split': 2}


## Deliverables
### (a) Confusion Matrix

In [44]:
#print confustion matrix
print(confusion_matrix(y_test1, best_dt_pred1))

[[2 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 2 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 2 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0]
 [1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 

### (c) (d) Precision, recall, f1 measure for each class; accuracy, macro-average f1 and weighted-average f1 of the model

In [45]:
#print classification report
print(classification_report(y_test1, best_dt_pred1))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         4
           1       0.00      0.00      0.00         2
           2       1.00      0.75      0.86         4
           3       0.50      0.33      0.40         3
           4       0.50      0.50      0.50         2
           5       0.50      0.50      0.50         2
           6       1.00      0.50      0.67         4
           7       0.40      0.67      0.50         3
           8       0.75      1.00      0.86         3
           9       0.60      0.75      0.67         4
          10       0.50      0.33      0.40         3
          11       0.50      0.75      0.60         4
          12       0.33      0.33      0.33         3
          13       0.40      0.50      0.44         4
          14       0.43      1.00      0.60         3
          15       1.00      0.67      0.80         3
          16       0.00      0.00      0.00         3
          17       0.50    

## Creating CSV file Best-DT-DS1

In [46]:
filename = './outputs/Best-DT-DS1.csv'

Best_DT_DS1 = pd.DataFrame(data=best_dt_pred1)
Best_DT_DS1.index = Best_DT_DS1.index + 1
Best_DT_DS1.to_csv(filename, header=None)

writer = open(filename, 'a')

writer.write("\nConfusion Matrix:\n\n")
writer.write(str(confusion_matrix(y_test1, best_dt_pred1)))
writer.write("\n\n\n")
writer.write("\nClassification Report:\n\n")
writer.write(str(classification_report(y_test1, best_dt_pred1)))

writer.close()
print("Output file Best-DT-DS1 created!")

Output file Best-DT-DS1 created!


# 2. Data Set 2

In [47]:
#Retrieve test data for dataset1 from csv file
test_set2 = pd.read_csv("Assig1-Dataset/test_with_label_2.csv", header=None)

#seperate values/labels from the test data
y_test2 = test_set2[1024] #the set of labels to all the data in x_test
x_test2 = test_set2.drop(1024, axis=1) #test data set

#Retrieve train set data for dataset1 from csv file
train_set2 = pd.read_csv("Assig1-Dataset/train_2.csv", header=None)

#seperate values/labels from the train data
target_train2 = train_set2[1024] #y_train, the set of labels to all the data in x_train
x_train2 = train_set2.drop(1024,axis=1) #the training data set

## Setting Classifier Parameters and creating model

In [48]:
#Setting Classifier parameters
parameters = {'criterion': ['gini', 'entropy'],
              'max_depth': [10, None],
              'min_samples_split': [0,1,2,3,4,5],
              'min_impurity_decrease': [0.0,0.1, 0.2,0.3,0.4,0.5],
              'class_weight': ['none', 'balanced']}

#DecisionTreeClassifier
clf = GridSearchCV(estimator=DecisionTreeClassifier(), param_grid=parameters, n_jobs=-1)

best_dt_2 = clf.fit(x_train2, target_train2) #fit is used to train the algo based on the training data
best_dt_pred2 = best_dt_2.predict(x_test2) #predictions based on the test data


## Display best hyperparameters

In [49]:
#print best hyperparameters
print("Best parameters: ")
print(best_dt_2.best_params_)

Best parameters: 
{'class_weight': 'balanced', 'criterion': 'gini', 'max_depth': None, 'min_impurity_decrease': 0.0, 'min_samples_split': 3}


## Deliverables
### (a) Confusion Matrix

In [50]:
#print confustion matrix
print(confusion_matrix(y_test2, best_dt_pred2))

[[ 41   5   3   0   1   0   2   0   2   1]
 [  4 107   1   1   1   0   3   1   4   3]
 [  2   0   4   0   1   1   0   0   4   3]
 [  1   1   0  12   1   0   0   0   0   0]
 [  4   2   0   1  25   3   1   1   1  12]
 [  1   0   2   0   2  41   0   0   1   8]
 [  2   2   0   0   1   0   5   0   3   2]
 [  0   0   0   0   0   0   0  15   0   0]
 [  1   1   0   0   1   1   0   0  41   5]
 [  5   3   2   0  13  11   2   0   2  87]]


### (c) (d) Precision, recall, f1 measure for each class; accuracy, macro-average f1 and weighted-average f1 of the model

In [51]:
#print classificaton report
print(classification_report(y_test2, best_dt_pred2))

              precision    recall  f1-score   support

           0       0.67      0.75      0.71        55
           1       0.88      0.86      0.87       125
           2       0.33      0.27      0.30        15
           3       0.86      0.80      0.83        15
           4       0.54      0.50      0.52        50
           5       0.72      0.75      0.73        55
           6       0.38      0.33      0.36        15
           7       0.88      1.00      0.94        15
           8       0.71      0.82      0.76        50
           9       0.72      0.70      0.71       125

    accuracy                           0.73       520
   macro avg       0.67      0.68      0.67       520
weighted avg       0.72      0.73      0.72       520



## Creating CSV file Best-DT-DS2

In [52]:
filename = './outputs/Best-DT-DS2.csv'

Best_DT_DS2 = pd.DataFrame(data=best_dt_pred2)
Best_DT_DS2.index = Best_DT_DS2.index + 1
Best_DT_DS2.to_csv(filename, header=None)

writer = open(filename, 'a')

writer.write("\nConfusion Matrix:\n\n")
writer.write(str(confusion_matrix(y_test2, best_dt_pred2)))
writer.write("\n\n\n")
writer.write("\nClassification Report:\n\n")
writer.write(str(classification_report(y_test2, best_dt_pred2)))

writer.close()
print("Output file Best-DT-DS2 created!")

Output file Best-DT-DS2 created!
