In [1]:
from sklearn import preprocessing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore') 
%matplotlib inline

In [2]:
letters = pd.read_csv("Assig1-Dataset/info_1.csv", header=0)

In [3]:
letters.head()

index symbol
0      0      A
1      1      B
2      2      C
3      3      D
4      4      E

In [4]:
numbers = pd.read_csv("Assig1-Dataset/info_1.csv", index_col=0, header=0, squeeze=True).to_dict()

In [5]:
print(numbers)

{0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E', 5: 'F', 6: 'G', 7: 'H', 8: 'I', 9: 'J', 10: 'K', 11: 'L', 12: 'M', 13: 'N', 14: 'O', 15: 'P', 16: 'Q', 17: 'R', 18: 'S', 19: 'T', 20: 'U', 21: 'V', 22: 'W', 23: 'X', 24: 'Y', 25: 'Z'}


In [7]:
test_set = pd.read_csv("Assig1-Dataset/test_with_label_1.csv", header=None)

In [8]:
test_set.head()

0     1     2     3     4     5     6     7     8     9     ...  1015  \
0     1     1     0     0     0     0     0     0     0     0  ...     1   
1     1     1     1     1     1     1     1     1     1     1  ...     0   
2     1     1     1     1     1     1     1     1     1     1  ...     1   
3     1     1     1     1     1     1     1     1     1     1  ...     0   
4     1     1     1     1     1     1     1     1     1     1  ...     1   

   1016  1017  1018  1019  1020  1021  1022  1023  1024  
0     1     1     1     1     1     1     1     1     4  
1     0     1     1     1     1     1     1     1    13  
2     1     1     1     1     1     1     1     1     7  
3     0     0     1     1     1     1     1     1     2  
4     1     1     1     1     1     1     1     1    18  

[5 rows x 1025 columns]

In [9]:
y_test = test_set[1024] #the set of labels to all the data in x_test
print(y_test)

0      4
1     13
2      7
3      2
4     18
      ..
75    18
76    15
77    17
78     6
79    19
Name: 1024, Length: 80, dtype: int64


In [10]:
X_test = test_set.drop(1024, axis=1) #test data set
print(X_test)

    0     1     2     3     4     5     6     7     8     9     ...  1014  \
0      1     1     0     0     0     0     0     0     0     0  ...     1   
1      1     1     1     1     1     1     1     1     1     1  ...     1   
2      1     1     1     1     1     1     1     1     1     1  ...     1   
3      1     1     1     1     1     1     1     1     1     1  ...     0   
4      1     1     1     1     1     1     1     1     1     1  ...     0   
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
75     1     1     1     1     1     1     1     1     1     0  ...     1   
76     1     1     1     1     1     1     1     0     0     1  ...     1   
77     1     1     1     1     1     1     0     0     0     0  ...     1   
78     1     1     1     1     1     1     1     1     1     1  ...     1   
79     1     1     0     0     0     0     0     0     0     0  ...     1   

    1015  1016  1017  1018  1019  1020  1021  1022  1023  
0      1     1  

In [11]:
training_set = pd.read_csv("Assig1-Dataset/train_1.csv", header=None)

In [12]:
print(training_set)

      0     1     2     3     4     5     6     7     8     9     ...  1015  \
0        1     1     1     1     1     1     1     1     1     1  ...     1   
1        1     1     1     1     1     1     1     1     1     1  ...     1   
2        1     1     1     1     1     1     1     0     0     0  ...     0   
3        1     1     1     1     1     1     0     0     0     1  ...     1   
4        1     1     1     1     1     1     1     1     1     1  ...     1   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1192     1     1     1     1     1     1     1     1     1     1  ...     0   
1193     1     1     1     1     1     1     1     1     1     1  ...     0   
1194     1     1     1     1     1     1     1     1     1     0  ...     1   
1195     0     1     1     1     1     1     1     1     1     1  ...     1   
1196     1     1     1     1     1     1     1     1     1     1  ...     1   

      1016  1017  1018  1019  1020  1021  1022  102

In [13]:
y_training = training_set[1024] #y_train, the set of labels to all the data in x_train
print(y_training)

0        1
1       14
2        4
3       12
4       20
        ..
1192     6
1193     6
1194     1
1195     1
1196    16
Name: 1024, Length: 1197, dtype: int64


In [14]:
X_training = training_set.drop(1024,axis=1) #the training data set

In [15]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_training, y_training)
y_pred = gnb.predict(X_test)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score

In [17]:
print(confusion_matrix(y_test, y_pred))

[[2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         4
           1       0.33      1.00      0.50         2
           2       1.00      0.75      0.86         4
           3       0.67      0.67      0.67         3
           4       0.00      0.00      0.00         2
           5       0.50      0.50      0.50         2
           6       0.67      0.50      0.57         4
           7       1.00      0.33      0.50         3
           8       1.00      1.00      1.00         3
           9       1.00      0.50      0.67         4
          10       0.50      0.33      0.40         3
          11       1.00      0.75      0.86         4
          12       0.29      0.67      0.40         3
          13       0.60      0.75      0.67         4
          14       1.00      1.00      1.00         3
          15       1.00      0.67      0.80         3
          16       0.60      1.00      0.75         3
          17       0.50    

In [22]:
X =  list(range(15))
y = [x * x for x in X]
print (X, y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]


In [23]:
print("Some labels do not appear in test vs prediction: ", set(y_test) - set(y_pred))

Some labels do not appear in test vs prediction:  {4}
