In [1]:
from sklearn import preprocessing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore') 
%matplotlib inline

In [2]:
letters = pd.read_csv("Assig1-Dataset/info_2.csv", header=0)

In [3]:
letters.head()

index symbol
0      0     pi
1      1  alpha
2      2   beta
3      3  sigma
4      4  gamma

In [4]:
numbers = pd.read_csv("Assig1-Dataset/info_2.csv", index_col=0, header=0, squeeze=True).to_dict()

In [5]:
print(numbers)

{0: 'pi', 1: 'alpha', 2: 'beta', 3: 'sigma', 4: 'gamma', 5: 'delta', 6: 'lambda', 7: 'omega', 8: 'mu', 9: 'xi'}


In [6]:
test_set = pd.read_csv("Assig1-Dataset/test_with_label_2.csv", header=None)

In [7]:
test_set.head()

0     1     2     3     4     5     6     7     8     9     ...  1015  \
0     1     1     1     1     1     1     1     1     1     1  ...     0   
1     1     1     1     1     1     1     1     1     1     1  ...     1   
2     1     1     1     1     1     1     1     1     1     1  ...     1   
3     1     1     1     1     1     1     1     1     1     1  ...     1   
4     1     1     1     1     1     1     1     1     1     1  ...     1   

   1016  1017  1018  1019  1020  1021  1022  1023  1024  
0     0     0     1     1     1     1     1     1     9  
1     1     1     1     1     1     1     1     1     0  
2     1     1     1     1     1     1     1     1     4  
3     1     1     1     1     1     1     1     1     5  
4     1     1     1     1     1     1     1     1     9  

[5 rows x 1025 columns]

In [8]:
y_test = test_set[1024] #the set of labels to all the data in x_test
print(y_test)

0      9
1      0
2      4
3      5
4      9
      ..
515    0
516    1
517    9
518    6
519    5
Name: 1024, Length: 520, dtype: int64


In [9]:
X_test = test_set.drop(1024, axis=1) #test data set
print(X_test)

     0     1     2     3     4     5     6     7     8     9     ...  1014  \
0       1     1     1     1     1     1     1     1     1     1  ...     0   
1       1     1     1     1     1     1     1     1     1     1  ...     1   
2       1     1     1     1     1     1     1     1     1     1  ...     1   
3       1     1     1     1     1     1     1     1     1     1  ...     1   
4       1     1     1     1     1     1     1     1     1     1  ...     0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
515     1     1     1     1     1     1     1     1     1     1  ...     1   
516     1     1     1     1     1     1     1     1     1     1  ...     1   
517     1     1     1     1     1     1     1     1     1     0  ...     1   
518     1     1     1     1     0     0     0     0     0     1  ...     1   
519     1     1     1     1     1     1     1     1     1     1  ...     1   

     1015  1016  1017  1018  1019  1020  1021  1022  1023  
0  

In [10]:
training_set = pd.read_csv("Assig1-Dataset/train_2.csv", header=None)

In [11]:
print(training_set)

      0     1     2     3     4     5     6     7     8     9     ...  1015  \
0        1     1     1     1     1     1     1     1     1     0  ...     1   
1        1     1     1     1     1     1     1     1     1     1  ...     1   
2        1     1     1     1     1     1     1     1     1     0  ...     1   
3        1     1     1     1     1     1     1     1     1     1  ...     0   
4        1     1     1     1     1     1     1     1     1     1  ...     1   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
7795     1     1     1     1     1     1     1     1     1     0  ...     1   
7796     1     1     1     1     1     1     1     1     0     0  ...     0   
7797     1     1     1     1     1     1     1     1     1     1  ...     1   
7798     1     1     1     1     1     1     1     1     0     0  ...     1   
7799     1     1     1     1     1     1     0     0     0     0  ...     1   

      1016  1017  1018  1019  1020  1021  1022  102

In [12]:
y_training = training_set[1024] #y_train, the set of labels to all the data in x_train
print(y_training)

0       9
1       0
2       9
3       4
4       9
       ..
7795    9
7796    6
7797    5
7798    4
7799    5
Name: 1024, Length: 7800, dtype: int64


In [13]:
X_training = training_set.drop(1024,axis=1) #the training data set

In [14]:
from sklearn.linear_model import Perceptron
per = Perceptron()
per.fit(X_training, y_training)
y_pred = per.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score

In [16]:
print(confusion_matrix(y_test, y_pred))

[[ 52   0   0   0   0   0   0   0   1   2]
 [  2 121   0   1   0   0   0   0   1   0]
 [  1   0   8   0   0   1   0   0   4   1]
 [  0   0   0  14   1   0   0   0   0   0]
 [ 10   1   0   0  27   4   0   0   2   6]
 [  0   0   1   1   1  49   0   0   0   3]
 [  2   6   1   0   0   0   5   0   1   0]
 [  0   0   0   0   0   0   0  15   0   0]
 [  4   2   0   0   0   0   0   0  42   2]
 [  6   1   1   0   6   6   1   0   1 103]]


In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.68      0.95      0.79        55
           1       0.92      0.97      0.95       125
           2       0.73      0.53      0.62        15
           3       0.88      0.93      0.90        15
           4       0.77      0.54      0.64        50
           5       0.82      0.89      0.85        55
           6       0.83      0.33      0.48        15
           7       1.00      1.00      1.00        15
           8       0.81      0.84      0.82        50
           9       0.88      0.82      0.85       125

    accuracy                           0.84       520
   macro avg       0.83      0.78      0.79       520
weighted avg       0.84      0.84      0.83       520



In [18]:
X =  list(range(15))
y = [x * x for x in X]
print (X, y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]
