In [1]:
import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import warnings

from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.metrics import classification_report, confusion_matrix, f1_score

warnings.filterwarnings('ignore') 
%matplotlib inline

# Database 1

## 1. Importing dataset

In [2]:
letters = pd.read_csv("Assig1-Dataset/info_1.csv", header=0)

In [3]:
letters.head()

index symbol
0      0      A
1      1      B
2      2      C
3      3      D
4      4      E

In [4]:
test_set = pd.read_csv("Assig1-Dataset/test_with_label_1.csv", header=None)

In [5]:
test_set.head()

0     1     2     3     4     5     6     7     8     9     ...  1015  \
0     1     1     0     0     0     0     0     0     0     0  ...     1   
1     1     1     1     1     1     1     1     1     1     1  ...     0   
2     1     1     1     1     1     1     1     1     1     1  ...     1   
3     1     1     1     1     1     1     1     1     1     1  ...     0   
4     1     1     1     1     1     1     1     1     1     1  ...     1   

   1016  1017  1018  1019  1020  1021  1022  1023  1024  
0     1     1     1     1     1     1     1     1     4  
1     0     1     1     1     1     1     1     1    13  
2     1     1     1     1     1     1     1     1     7  
3     0     0     1     1     1     1     1     1     2  
4     1     1     1     1     1     1     1     1    18  

[5 rows x 1025 columns]

In [6]:
y_test = test_set[1024] #the set of labels to all the data in x_test
X_test = test_set.drop(1024, axis=1) #test data set
training_set = pd.read_csv("Assig1-Dataset/train_1.csv", header=None)
y_training = training_set[1024] #y_train, the set of labels to all the data in x_train
X_training = training_set.drop(1024,axis=1) #the training data set

## 2. Training - Running default parameter GNB

In [7]:
per = Perceptron()
per.fit(X_training, y_training)
y_pred = per.predict(X_test)

## Deliverables

### (b) Confusion Matrix

In [8]:
per_confusion_matrix = confusion_matrix(y_test, y_pred)
print(per_confusion_matrix)

[[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 

### (c) (d) Precision, recall, f1 measure for each class; accuracy, macro-average f1 and weighted-average f1 of the model
#### From Classification Report

In [9]:
per_classification_report = classification_report(y_test, y_pred)
print(per_classification_report)

              precision    recall  f1-score   support

           0       0.60      0.75      0.67         4
           1       1.00      1.00      1.00         2
           2       1.00      0.75      0.86         4
           3       1.00      1.00      1.00         3
           4       1.00      1.00      1.00         2
           5       0.33      0.50      0.40         2
           6       1.00      0.75      0.86         4
           7       0.33      0.33      0.33         3
           8       1.00      1.00      1.00         3
           9       0.75      0.75      0.75         4
          10       0.33      0.33      0.33         3
          11       0.80      1.00      0.89         4
          12       0.50      0.33      0.40         3
          13       1.00      1.00      1.00         4
          14       1.00      1.00      1.00         3
          15       0.75      1.00      0.86         3
          16       0.75      1.00      0.86         3
          17       0.43    

### (a) CSV output

In [10]:

filename = './outputs/PER-DS1.csv'

PER_DS1 = pd.DataFrame(y_pred)
PER_DS1.index = PER_DS1.index + 1 #To follow assignment example
PER_DS1.to_csv(filename, header=False)

writer = open(filename, 'a')

writer.write("\nConfusion Matrix:\n\n")
writer.write(str(per_confusion_matrix))
writer.write("\n\n\n")
writer.write("\nClassification Report:\n\n")
writer.write(str(per_classification_report))

writer.close()

# Database 2

## 1. Importing dataset

In [11]:
letters = pd.read_csv("Assig1-Dataset/info_2.csv", header=0)

In [12]:
letters.head()

index symbol
0      0     pi
1      1  alpha
2      2   beta
3      3  sigma
4      4  gamma

In [13]:
test_set = pd.read_csv("Assig1-Dataset/test_with_label_2.csv", header=None)

In [14]:
test_set.head()

0     1     2     3     4     5     6     7     8     9     ...  1015  \
0     1     1     1     1     1     1     1     1     1     1  ...     0   
1     1     1     1     1     1     1     1     1     1     1  ...     1   
2     1     1     1     1     1     1     1     1     1     1  ...     1   
3     1     1     1     1     1     1     1     1     1     1  ...     1   
4     1     1     1     1     1     1     1     1     1     1  ...     1   

   1016  1017  1018  1019  1020  1021  1022  1023  1024  
0     0     0     1     1     1     1     1     1     9  
1     1     1     1     1     1     1     1     1     0  
2     1     1     1     1     1     1     1     1     4  
3     1     1     1     1     1     1     1     1     5  
4     1     1     1     1     1     1     1     1     9  

[5 rows x 1025 columns]

In [15]:
y_test = test_set[1024] #the set of labels to all the data in x_test
X_test = test_set.drop(1024, axis=1) #test data set
training_set = pd.read_csv("Assig1-Dataset/train_2.csv", header=None)
y_training = training_set[1024] #y_train, the set of labels to all the data in x_train
X_training = training_set.drop(1024,axis=1) #the training data set

## 2. Training - Running default parameter GNB

In [16]:
per = Perceptron()
per.fit(X_training, y_training)
y_pred = per.predict(X_test)

## Deliverables

### (b) Confusion Matrix

In [17]:
per_confusion_matrix = confusion_matrix(y_test, y_pred)
print(per_confusion_matrix)

[[ 52   0   0   0   0   0   0   0   1   2]
 [  2 121   0   1   0   0   0   0   1   0]
 [  1   0   8   0   0   1   0   0   4   1]
 [  0   0   0  14   1   0   0   0   0   0]
 [ 10   1   0   0  27   4   0   0   2   6]
 [  0   0   1   1   1  49   0   0   0   3]
 [  2   6   1   0   0   0   5   0   1   0]
 [  0   0   0   0   0   0   0  15   0   0]
 [  4   2   0   0   0   0   0   0  42   2]
 [  6   1   1   0   6   6   1   0   1 103]]


### (c) (d) Precision, recall, f1 measure for each class; accuracy, macro-average f1 and weighted-average f1 of the model
#### From Classification Report

In [18]:
per_classification_report = classification_report(y_test, y_pred)
print(per_classification_report)

              precision    recall  f1-score   support

           0       0.68      0.95      0.79        55
           1       0.92      0.97      0.95       125
           2       0.73      0.53      0.62        15
           3       0.88      0.93      0.90        15
           4       0.77      0.54      0.64        50
           5       0.82      0.89      0.85        55
           6       0.83      0.33      0.48        15
           7       1.00      1.00      1.00        15
           8       0.81      0.84      0.82        50
           9       0.88      0.82      0.85       125

    accuracy                           0.84       520
   macro avg       0.83      0.78      0.79       520
weighted avg       0.84      0.84      0.83       520



### (a) CSV output

In [19]:

filename = './outputs/PER-DS2.csv'

PER_DS2 = pd.DataFrame(y_pred)
PER_DS2.index = PER_DS2.index + 1 #To follow assignment example
PER_DS2.to_csv(filename, header=False)

writer = open(filename, 'a')

writer.write("\nConfusion Matrix:\n\n")
writer.write(str(per_confusion_matrix))
writer.write("\n\n\n")
writer.write("\nClassification Report:\n\n")
writer.write(str(per_classification_report))

writer.close()